version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      API_PORT: ${API_PORT}
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 80:80

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      API_PORT: ${API_PORT}
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "yarn workspace api healthcheck"]
      interval: 1s
      retries: 10
    depends_on:
      - migrate

  migrate:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      retries: 10
