services:
  router:
    image: nginx:stable
    environment:
      API_PORT: ${API_PORT}
      APP_PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template

  app:
    build:
      target: base
    environment:
      APP_PORT: ${APP_PORT}
    volumes:
      - ./app:/home/node/app/app
      - ./api:/home/node/app/api
      - ./lib:/home/node/app/lib
      - ./db:/home/node/app/db

  api:
    build:
      target: base
    volumes:
      - ./api:/home/node/app/api
      - ./db:/home/node/app/db
      - ./lib:/home/node/app/lib
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229

  db:
    ports:
      - ${DB_PORT}:5432
