name: tests

on: [push, pull_request]

jobs:
  tests:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Start app
        run: yarn dev --detach

      - name: Run unit and integration tests
        run: yarn workspace tests test

  features:
    name: Acceptance tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install

      - name: Start app
        run: yarn start --detach

      - name: Run acceptance tests
        run: yarn workspace features test
        env:
          CYPRESS_BASE_URL: http://localhost
